# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SSI_top.xdc

# Block Designs: bd/XDMA/XDMA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA || ORIG_REF_NAME==XDMA} -quiet] -quiet

# IP: bd/XDMA/ip/XDMA_xdma_0_0/XDMA_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_xdma_0_0 || ORIG_REF_NAME==XDMA_xdma_0_0} -quiet] -quiet

# IP: bd/XDMA/ip/XDMA_blk_mem_gen_0_0/XDMA_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_blk_mem_gen_0_0 || ORIG_REF_NAME==XDMA_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/XDMA/ip/XDMA_axi_bram_ctrl_0_4/XDMA_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_axi_bram_ctrl_0_4 || ORIG_REF_NAME==XDMA_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/XDMA/ip/XDMA_axi_bram_ctrl_0_5/XDMA_axi_bram_ctrl_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==XDMA_axi_bram_ctrl_0_5 || ORIG_REF_NAME==XDMA_axi_bram_ctrl_0_5} -quiet] -quiet

# XDC: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.gen/sources_1/bd/XDMA/XDMA_ooc.xdc
