# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.srcs/sources_1/bd/XDMA/ip/XDMA_blk_mem_gen_0_0/XDMA_blk_mem_gen_0_0.xci
# IP: The module: 'XDMA_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.gen/sources_1/bd/XDMA/ip/XDMA_blk_mem_gen_0_0/XDMA_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.srcs/sources_1/bd/XDMA/ip/XDMA_blk_mem_gen_0_0/XDMA_blk_mem_gen_0_0.xci
# IP: The module: 'XDMA_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.gen/sources_1/bd/XDMA/ip/XDMA_blk_mem_gen_0_0/XDMA_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
