# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.srcs/sources_1/bd/XDMA/ip/XDMA_axi_bram_ctrl_0_5/XDMA_axi_bram_ctrl_0_5.xci
# IP: The module: 'XDMA_axi_bram_ctrl_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.gen/sources_1/bd/XDMA/ip/XDMA_axi_bram_ctrl_0_5/XDMA_axi_bram_ctrl_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_axi_bram_ctrl_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.srcs/sources_1/bd/XDMA/ip/XDMA_axi_bram_ctrl_0_5/XDMA_axi_bram_ctrl_0_5.xci
# IP: The module: 'XDMA_axi_bram_ctrl_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zcy/Desktop/new_prj/XDMA_SSI/XDMA_SSI.gen/sources_1/bd/XDMA/ip/XDMA_axi_bram_ctrl_0_5/XDMA_axi_bram_ctrl_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_axi_bram_ctrl_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
